version: '3'

services:
  db:
    image: mongo:4.4
    container_name: brevet-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - brevet-network

  laptop:
    build: ./laptop
    container_name: brevet-laptop
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/
    networks:
      - brevet-network

  website:
    build: ./website
    container_name: brevet-website
    ports:
      - "8080:80"
    depends_on:
      - laptop
    networks:
      - brevet-network

volumes:
  mongo-data:

networks:
  brevet-network:
    driver: bridge